### ISSUE TITLE
Build fails when ViSearchSDK is imported inside the library. 

### ISSUE THREAD

**Issue by beniranjan91** [visenze/visearch-sdk-swift#40]
Step 1: I have added the xcode project as per instructions. 
            Issue:  I got a issue that .xcframework not found inside the carthage/build folder, 
            Hack I tried: so I did a carthage update. And  added the visearchsdk.xcodeproject into my project after this build got successful. 

Step 2: Import ViSearchSDK and initialise the search with appkey and placement . 
            Issue: Build fails only with few warning, sometimes it throws cannot find visearchsdk near import statement. 

Step 3: After these 2 steps above, I dragged the entire SDK folder into my project and did other steps as per instructions. 
Moved the (blueicon) visearchsdk.xcodeproject beneath my project(blueicon). 
             Issue: Inside the visenseanalytics files , the import statement throws error. 

Please provide a solution for this problem...

**Comment by thehung111** [comment]
Have you run `carthage update --use-xcframeworks`. It is mentioned in Developer Notes:
https://github.com/visenze/visearch-sdk-swift#8-developer-notes
The Xcode project needs to pull a dependency for tracking.

**Comment by beniranjan91** [comment]
Yes. Got the xcframeworks file only after the carthage update.
